openapi: "3.0.0"
info:
  description: "API de consultation des données vendeurs"
  version: "0.2.0_tag"
  title: "Weft_Sellers_Informations"
tags:
- name: "Company"
- name: "Establishment"
- name: "OrangeApiStatus"
paths:
  /siret/{siret}/party:
    get:
      tags:
      - "Company"
      operationId: "companyParty"
      summary: "party company"
      parameters:
      - name: "siret"
        required: true
        in: "path"
        schema:
          type: "string"
      responses:
        "200":
          description: "Ok"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/Party"
        "400":
          description: "Bad Request\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "404":
          description: "Not Found\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "405":
          description: "Method Not Allowed\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "422":
          description: "Unprocessable entity\n\nBusiness error"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "500":
          description: "Internal Server Error\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "503":
          description: "Service Unavailable\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
  /ideta/{ideta}/party:
    get:
      tags:
      - "Establishment"
      operationId: "establishmentParty"
      summary: "party establishment"
      parameters:
      - name: "ideta"
        required: true
        in: "path"
        schema:
          type: "string"
      responses:
        "200":
          description: "Ok"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/Party"
        "400":
          description: "Bad Request\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "404":
          description: "Not Found\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "405":
          description: "Method Not Allowed\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "422":
          description: "Unprocessable entity\n\nBusiness error"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "500":
          description: "Internal Server Error\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "503":
          description: "Service Unavailable\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
  /status:
    get:
      tags:
      - "OrangeApiStatus"
      operationId: "statusGet"
      summary: "get status"
      description: "See [Orange recommendation](https://recommendations.innov.intraorange/designing-orange-api/#status-path)"
      responses:
        "200":
          description: "Ok"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiStatus"
        "400":
          description: "Bad Request\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "404":
          description: "Not Found\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "405":
          description: "Method Not Allowed\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "422":
          description: "Unprocessable entity\n\nBusiness error"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "500":
          description: "Internal Server Error\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
        "503":
          description: "Service Unavailable\n\n"
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/OrangeApiError"
servers:
- url: "/v1"
components:
  schemas:
    Company:
      type: "object"
      properties:
        siret:
          type: "string"
          pattern: "\\d{14}"
    Establishment:
      type: "object"
      properties:
        ideta:
          type: "string"
    Party:
      description: "Informations Party (informations sur le vendeur)"
      type: "object"
      properties:
        civility:
          description: "Civilité du vendeur"
          type: "string"
        email:
          description: "Email du vendeur"
          type: "string"
          format: "email"
        givenName:
          description: "Prénom du vendeur"
          type: "string"
        name:
          description: "Nom du vendeur"
          type: "string"
    OrangeApiComponent:
      description: "A component your service requires (other web service, database,\
        \ etc) to be fully functional.  See [Orange Recommendation](https://recommendations.innov.intraorange/designing-orange-api/#status-path)"
      required:
      - "status"
      - "name"
      - "version"
      type: "object"
      properties:
        status:
          description: "Component status ok | ko"
          $ref: "#/components/schemas/OrangeApiStatusValue"
        name:
          description: "Component internal name."
          type: "string"
        version:
          description: "major.minor.patch see [semver.org](https://semver.org/) or\
            \ G00R00C00"
          type: "string"
    OrangeApiError:
      description: "See [Orange recommendation](https://recommendations.innov.intraorange/designing-orange-api/#error-format)"
      required:
      - "code"
      - "message"
      type: "object"
      properties:
        code:
          description: "An integer coding the error type. This is given to caller\
            \ so he can translate them if required."
          type: "integer"
          format: "int32"
        message:
          description: "A short localized string that describes the error."
          type: "string"
        description:
          description: "(optional) A long localized error description if needed. It\
            \ can contain precise information about which parameter is missing, or\
            \ what are the identifier acceptable values."
          type: "string"
        infoURL:
          description: "(optional) A URL to online documentation that provides more\
            \ information about the error."
          type: "string"
    OrangeApiStatus:
      description: "Reflect service or component health. See [Orange Recommendation](https://recommendations.innov.intraorange/designing-orange-api/#status-path)"
      required:
      - "status"
      - "name"
      - "version"
      type: "object"
      properties:
        status:
          description: "Service status ok | ko"
          $ref: "#/components/schemas/OrangeApiStatusValue"
        name:
          description: "Your service internal name."
          type: "string"
        version:
          description: "major.minor.patch see [semver.org](https://semver.org/) or\
            \ G00R00C00"
          type: "string"
        components:
          description: "Each array entry represents a component your service requires\
            \ (other web service, database, etc) to be fully functional"
          type: "array"
          items:
            $ref: "#/components/schemas/OrangeApiComponent"
    OrangeApiStatusValue:
      description: "status ok | ko.  See [Orange Recommendation](https://recommendations.innov.intraorange/designing-orange-api/#status-path)"
      type: "string"
      enum:
      - "ok"
      - "ko"
